################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
K_SRCS := 
LD_SRCS := 
S67_SRCS := 
CMD_SRCS := 
CXX_SRCS := 
CMD_UPPER_SRCS := 
C43_SRCS := 
S55_SRCS := 
LD_UPPER_SRCS := 
C62_SRCS := 
S_UPPER_SRCS := 
A_SRCS := 
C55_SRCS := 
SA_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S62_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S??_SRCS := 
C++_SRCS := 
CLA_SRCS := 
ASM_UPPER_SRCS := 
C_SRCS := 
C67_SRCS := 
S_SRCS := 
S43_SRCS := 
OPT_SRCS := 
C64_SRCS := 
C??_SRCS := 
CC_SRCS := 
S64_SRCS := 
OBJS := 
S_DEPS := 
S_UPPER_DEPS := 
S62_DEPS := 
C64_DEPS := 
ASM_DEPS := 
CC_DEPS := 
S55_DEPS := 
C67_DEPS := 
C??_DEPS := 
CLA_DEPS := 
CPP_DEPS := 
TMS470_EXECUTABLE_OUTPUTS := 
S??_DEPS := 
C_DEPS := 
C62_DEPS := 
CXX_DEPS := 
C++_DEPS := 
ASM_UPPER_DEPS := 
K_DEPS := 
C43_DEPS := 
S67_DEPS := 
SA_DEPS := 
S43_DEPS := 
OPT_DEPS := 
S64_DEPS := 
C_UPPER_DEPS := 
C55_DEPS := 
CPP_DEPS__QUOTED := 
C67_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
TMS470_EXECUTABLE_OUTPUTS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
CLA_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
S67_DEPS__QUOTED := 
C_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
S_DEPS__QUOTED := 
S??_DEPS__QUOTED := 
K_DEPS__QUOTED := 
C64_DEPS__QUOTED := 
C++_DEPS__QUOTED := 
OBJS__QUOTED := 
S43_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
C55_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
S62_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
S64_DEPS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
source \
CMSIS/ti_math_Cortex_R4_lspf \
CMSIS/ti_math_Cortex_R4_lspf/Source/TransformFunctions \
CMSIS/ti_math_Cortex_R4_lspf/Source/SupportFunctions \
CMSIS/ti_math_Cortex_R4_lspf/Source/StatisticsFunctions \
CMSIS/ti_math_Cortex_R4_lspf/Source/MatrixFunctions \
CMSIS/ti_math_Cortex_R4_lspf/Source/FilteringFunctions \
CMSIS/ti_math_Cortex_R4_lspf/Source/FastMathFunctions \
CMSIS/ti_math_Cortex_R4_lspf/Source/ControllerFunctions \
CMSIS/ti_math_Cortex_R4_lspf/Source/ComplexMathFunctions \
CMSIS/ti_math_Cortex_R4_lspf/Source/CommonTables \
CMSIS/ti_math_Cortex_R4_lspf/Source/BasicMathFunctions \
CMSIS/ti_math_Cortex_R4_l \
CMSIS/ti_math_Cortex_R4_l/Source/TransformFunctions \
CMSIS/ti_math_Cortex_R4_l/Source/SupportFunctions \
CMSIS/ti_math_Cortex_R4_l/Source/StatisticsFunctions \
CMSIS/ti_math_Cortex_R4_l/Source/MatrixFunctions \
CMSIS/ti_math_Cortex_R4_l/Source/FilteringFunctions \
CMSIS/ti_math_Cortex_R4_l/Source/FastMathFunctions \
CMSIS/ti_math_Cortex_R4_l/Source/ControllerFunctions \
CMSIS/ti_math_Cortex_R4_l/Source/ComplexMathFunctions \
CMSIS/ti_math_Cortex_R4_l/Source/CommonTables \
CMSIS/ti_math_Cortex_R4_l/Source/BasicMathFunctions \
CMSIS/ti_math_Cortex_R4_l/Release \
CMSIS/ti_math_Cortex_R4_l/Release/Source/TransformFunctions \
CMSIS/ti_math_Cortex_R4_l/Release/Source/SupportFunctions \
CMSIS/ti_math_Cortex_R4_l/Release/Source/StatisticsFunctions \
CMSIS/ti_math_Cortex_R4_l/Release/Source/MatrixFunctions \
CMSIS/ti_math_Cortex_R4_l/Release/Source/FilteringFunctions \
CMSIS/ti_math_Cortex_R4_l/Release/Source/FastMathFunctions \
CMSIS/ti_math_Cortex_R4_l/Release/Source/ControllerFunctions \
CMSIS/ti_math_Cortex_R4_l/Release/Source/ComplexMathFunctions \
CMSIS/ti_math_Cortex_R4_l/Release/Source/CommonTables \
CMSIS/ti_math_Cortex_R4_l/Release/Source/BasicMathFunctions \
CMSIS/ti_math_Cortex_R4_l/Release/HelperFunc/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_variance_example \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_variance_example/CCS/Debug \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_variance_example/CCS/Debug/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_variance_example/CCS/Debug/HelperFunc/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_sin_cos_example \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_sin_cos_example/CCS/Debug \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_sin_cos_example/CCS/Debug/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_sin_cos_example/CCS/Debug/HelperFunc/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_signal_converge_example \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_signal_converge_example/CCS/Debug \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_signal_converge_example/CCS/Debug/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_signal_converge_example/CCS/Debug/HelperFunc/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_matrix_example \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_matrix_example/CCS/Debug \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_matrix_example/CCS/Debug/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_matrix_example/CCS/Debug/HelperFunc/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_graphic_equalizer_example \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_graphic_equalizer_example/CCS/Debug \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_graphic_equalizer_example/CCS/Debug/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_graphic_equalizer_example/CCS/Debug/HelperFunc/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_fir_example \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_fir_example/CCS/Debug \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_fir_example/CCS/Debug/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_fir_example/CCS/Debug/HelperFunc/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_fir_example/ARM/debug \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_fft_bin_example \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_fft_bin_example/CCS/Debug \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_fft_bin_example/CCS/Debug/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_fft_bin_example/CCS/Debug/HelperFunc/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_dotproduct_example \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_dotproduct_example/CCS/Debug \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_dotproduct_example/CCS/Debug/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_dotproduct_example/CCS/Debug/HelperFunc/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_convolution_example \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_convolution_example/CCS/Debug \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_convolution_example/CCS/Debug/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_convolution_example/CCS/Debug/HelperFunc/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_class_marks_example \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_class_marks_example/CCS/Debug \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/arm_class_marks_example/CCS/Debug/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/HelperFunc/Source \
CMSIS/ti_math_Cortex_R4_l/Release/Examples/DeviceSupport/ARM/MDK/Source \
CMSIS/ti_math_Cortex_R4_l/Release/DeviceSupport/TI/Source \
CMSIS/ti_math_Cortex_R4_l/Release/DeviceSupport/ARM/MDK/Source \
CMSIS/ti_math_Cortex_R4_bspf \
CMSIS/ti_math_Cortex_R4_bspf/Source/TransformFunctions \
CMSIS/ti_math_Cortex_R4_bspf/Source/SupportFunctions \
CMSIS/ti_math_Cortex_R4_bspf/Source/StatisticsFunctions \
CMSIS/ti_math_Cortex_R4_bspf/Source/MatrixFunctions \
CMSIS/ti_math_Cortex_R4_bspf/Source/FilteringFunctions \
CMSIS/ti_math_Cortex_R4_bspf/Source/FastMathFunctions \
CMSIS/ti_math_Cortex_R4_bspf/Source/ControllerFunctions \
CMSIS/ti_math_Cortex_R4_bspf/Source/ComplexMathFunctions \
CMSIS/ti_math_Cortex_R4_bspf/Source/CommonTables \
CMSIS/ti_math_Cortex_R4_bspf/Source/BasicMathFunctions \
CMSIS/ti_math_Cortex_R4_b \
CMSIS/ti_math_Cortex_R4_b/Source/TransformFunctions \
CMSIS/ti_math_Cortex_R4_b/Source/SupportFunctions \
CMSIS/ti_math_Cortex_R4_b/Source/StatisticsFunctions \
CMSIS/ti_math_Cortex_R4_b/Source/MatrixFunctions \
CMSIS/ti_math_Cortex_R4_b/Source/FilteringFunctions \
CMSIS/ti_math_Cortex_R4_b/Source/FastMathFunctions \
CMSIS/ti_math_Cortex_R4_b/Source/ControllerFunctions \
CMSIS/ti_math_Cortex_R4_b/Source/ComplexMathFunctions \
CMSIS/ti_math_Cortex_R4_b/Source/CommonTables \
CMSIS/ti_math_Cortex_R4_b/Source/BasicMathFunctions \
CMSIS/Source \
CMSIS/Source/TransformFunctions \
CMSIS/Source/SupportFunctions \
CMSIS/Source/StatisticsFunctions \
CMSIS/Source/MatrixFunctions \
CMSIS/Source/FilteringFunctions \
CMSIS/Source/FastMathFunctions \
CMSIS/Source/ControllerFunctions \
CMSIS/Source/ComplexMathFunctions \
CMSIS/Source/CommonTables \
CMSIS/Source/BasicMathFunctions \
CMSIS/Lib \
CMSIS/HelperFunc/Source \
CMSIS/Examples \
CMSIS/Examples/arm_variance_example \
CMSIS/Examples/arm_variance_example/CCS/Debug \
CMSIS/Examples/arm_variance_example/CCS/Debug/Source \
CMSIS/Examples/arm_variance_example/CCS/Debug/HelperFunc/Source \
CMSIS/Examples/arm_sin_cos_example \
CMSIS/Examples/arm_sin_cos_example/CCS/Debug \
CMSIS/Examples/arm_sin_cos_example/CCS/Debug/Source \
CMSIS/Examples/arm_sin_cos_example/CCS/Debug/HelperFunc/Source \
CMSIS/Examples/arm_signal_converge_example \
CMSIS/Examples/arm_signal_converge_example/CCS/Debug \
CMSIS/Examples/arm_signal_converge_example/CCS/Debug/Source \
CMSIS/Examples/arm_signal_converge_example/CCS/Debug/HelperFunc/Source \
CMSIS/Examples/arm_matrix_example \
CMSIS/Examples/arm_matrix_example/CCS/Debug \
CMSIS/Examples/arm_matrix_example/CCS/Debug/Source \
CMSIS/Examples/arm_matrix_example/CCS/Debug/HelperFunc/Source \
CMSIS/Examples/arm_graphic_equalizer_example \
CMSIS/Examples/arm_graphic_equalizer_example/CCS/Debug \
CMSIS/Examples/arm_graphic_equalizer_example/CCS/Debug/Source \
CMSIS/Examples/arm_graphic_equalizer_example/CCS/Debug/HelperFunc/Source \
CMSIS/Examples/arm_fir_example \
CMSIS/Examples/arm_fir_example/CCS/Debug \
CMSIS/Examples/arm_fir_example/CCS/Debug/Source \
CMSIS/Examples/arm_fir_example/CCS/Debug/HelperFunc/Source \
CMSIS/Examples/arm_fir_example/ARM/debug \
CMSIS/Examples/arm_fft_bin_example \
CMSIS/Examples/arm_fft_bin_example/CCS/Debug \
CMSIS/Examples/arm_fft_bin_example/CCS/Debug/Source \
CMSIS/Examples/arm_fft_bin_example/CCS/Debug/HelperFunc/Source \
CMSIS/Examples/arm_dotproduct_example \
CMSIS/Examples/arm_dotproduct_example/CCS/Debug \
CMSIS/Examples/arm_dotproduct_example/CCS/Debug/Source \
CMSIS/Examples/arm_dotproduct_example/CCS/Debug/HelperFunc/Source \
CMSIS/Examples/arm_convolution_example \
CMSIS/Examples/arm_convolution_example/CCS/Debug \
CMSIS/Examples/arm_convolution_example/CCS/Debug/Source \
CMSIS/Examples/arm_convolution_example/CCS/Debug/HelperFunc/Source \
CMSIS/Examples/arm_class_marks_example \
CMSIS/Examples/arm_class_marks_example/CCS/Debug \
CMSIS/Examples/arm_class_marks_example/CCS/Debug/Source \
CMSIS/Examples/HelperFunc/Source \
CMSIS/Examples/DeviceSupport/ARM/MDK/Source \
CMSIS/DeviceSupport/TI/Source \
CMSIS/DeviceSupport/ARM/MDK/Source \

