/** @file pinmux.c 
*   @brief PINMUX Driver Implementation File
*   @date 15.Mar.2012
*   @version 03.01.00
*
*/

/* (c) Texas Instruments 2009-2012, All rights reserved. */

/* Include Files */

#include "pinmux.h"

#define PINMUX_SET(REG, BALLID, MUX)								\
				pinMuxReg->PINMUX##REG## = (pinMuxReg->PINMUX##REG## & PINMUX_BALL_##BALLID##_MASK) | (PINMUX_BALL_##BALLID##_##MUX##)

#define PINMUX_GATE_EMIF_CLK_ENABLE		\
			pinMuxReg->PINMUX29 = (pinMuxReg->PINMUX29 & PINMUX_GATE_EMIF_CLK_MASK) | PINMUX_GATE_EMIF_CLK

#define PINMUX_GIOB_DISABLE_HET2_ENABLE	\
			pinMuxReg->PINMUX29 = (pinMuxReg->PINMUX29 & PINMUX_GIOB_DISABLE_HET2_MASK) | PINMUX_GIOB_DISABLE_HET2
			
#define PINMUX_ALT_ADC_TRIGGER_SELECT(num)	\
			pinMuxReg->PINMUX30 = (pinMuxReg->PINMUX30 & PINMUX_ALT_ADC_TRIGGER_MASK) | (PINMUX_ALT_ADC_TRIGGER_##num##)
			
#define PINMUX_ETHERNET_SELECT(interface)	\
			pinMuxReg->PINMUX29 = (pinMuxReg->PINMUX29 & PINMUX_ETHERNET_MASK) | (PINMUX_ETHERNET_##interface##)

#define PINMUX_ETPWM1_EQEPERR_ENABLE(interface)		\
			pinMuxReg->PINMUX41 = (pinMuxReg->PINMUX41 & PINMUX_ETPWM1_MASK) | (PINMUX_ETPWM1_##interface##)

#define PINMUX_ETPWM2_EQEPERR_ENABLE(interface)		\
			pinMuxReg->PINMUX41 = (pinMuxReg->PINMUX41 & PINMUX_ETPWM2_MASK) | (PINMUX_ETPWM2_##interface##)

#define PINMUX_ETPWM3_EQEPERR_ENABLE(interface)		\
			pinMuxReg->PINMUX41 = (pinMuxReg->PINMUX41 & PINMUX_ETPWM3_MASK) | (PINMUX_ETPWM3_##interface##)

#define PINMUX_ETPWM4_EQEPERR_ENABLE(interface)		\
			pinMuxReg->PINMUX41 = (pinMuxReg->PINMUX41 & PINMUX_ETPWM4_MASK) | (PINMUX_ETPWM4_##interface##)

#define PINMUX_ETPWM5_EQEPERR_ENABLE(interface)		\
			pinMuxReg->PINMUX42 = (pinMuxReg->PINMUX42 & PINMUX_ETPWM5_MASK) | (PINMUX_ETPWM5_##interface##)

#define PINMUX_ETPWM6_EQEPERR_ENABLE(interface)		\
			pinMuxReg->PINMUX42 = (pinMuxReg->PINMUX42 & PINMUX_ETPWM6_MASK) | (PINMUX_ETPWM6_##interface##)

#define PINMUX_ETPWM7_EQEPERR_ENABLE(interface)		\
			pinMuxReg->PINMUX42 = (pinMuxReg->PINMUX42 & PINMUX_ETPWM7_MASK) | (PINMUX_ETPWM7_##interface##)

#define PINMUX_ETPWM_TZ1_ENABLE(interface)		\
			pinMuxReg->PINMUX46 = (pinMuxReg->PINMUX46 & PINMUX_TZ1_SHIFT) | (PINMUX_TZ1_##interface##)

#define PINMUX_ETPWM_TZ2_ENABLE(interface)		\
			pinMuxReg->PINMUX46 = (pinMuxReg->PINMUX46 & PINMUX_TZ2_SHIFT) | (PINMUX_TZ2_##interface##)

#define PINMUX_ETPWM_TZ3_ENABLE(interface)		\
			pinMuxReg->PINMUX47 = (pinMuxReg->PINMUX47 & PINMUX_TZ3_SHIFT) | (PINMUX_TZ3_##interface##)

#define PINMUX_ETPWM_EPWM1SYNCI_ENABLE(interface)		\
			pinMuxReg->PINMUX47 = (pinMuxReg->PINMUX47 & PINMUX_EPWM1SYNCI_SHIFT) | (PINMUX_EPWM1SYNCI_##interface##)

#define PINMUX_ETPWM_TIME_BASE_SYNC_ENABLE		\
			pinMuxReg->PINMUX36 = (pinMuxReg->PINMUX36 & PINMUX_ETPWM_TIME_BASE_SYNC_MASK) | PINMUX_ETPWM_TIME_BASE_SYNC

#define PINMUX_ETPWM_TBCLK_SYNC_ENABLE 		\
			pinMuxReg->PINMUX37 = (pinMuxReg->PINMUX37 & PINMUX_ETPWM_TBCLK_SYNC_MASK) | PINMUX_ETPWM_TBCLK_SYNC




/* USER CODE BEGIN (0) */
/* USER CODE END */

void muxInit(void){

/* USER CODE BEGIN (1) */
/* USER CODE END */

	/* Enable Pin Muxing */
	kickerReg->KICKER0 = 0x83E70B13;
	kickerReg->KICKER1 = 0x95A4F1E0;
	
/* USER CODE BEGIN (2) */
/* USER CODE END */

        pinMuxReg->PINMUX0 = PINMUX_BALL_W10_GIOB_3 | PINMUX_BALL_A5_GIOA_0 | PINMUX_BALL_C3_MIBSPI3NCS_3 | PINMUX_BALL_B2_MIBSPI3NCS_2;
	
	pinMuxReg->PINMUX1 = PINMUX_BALL_C2_GIOA_1 | PINMUX_BALL_E3_HET1_11;
	
	pinMuxReg->PINMUX2 = PINMUX_BALL_C1_EQEP2I | PINMUX_BALL_E1_GIOA_3 | PINMUX_BALL_B5_GIOA_5;
	
	pinMuxReg->PINMUX3 = PINMUX_BALL_B3_HET1_22 | PINMUX_BALL_H3_GIOA_6;
	
	pinMuxReg->PINMUX4 = PINMUX_BALL_M1_GIOA_7 | PINMUX_BALL_V2_EQEP2A | PINMUX_BALL_U1_EQEP2B;
	
	pinMuxReg->PINMUX5 = PINMUX_BALL_K18_HET1_0 | PINMUX_BALL_W5_HET1_02 | PINMUX_BALL_V6_HET1_05;
	
	pinMuxReg->PINMUX6 = PINMUX_BALL_T1_HET1_07 | PINMUX_BALL_V7_HET1_09;
	
	pinMuxReg->PINMUX7 = PINMUX_BALL_V5_MIBSPI3NCS_1 | PINMUX_BALL_W3_HET1_06;
	
	pinMuxReg->PINMUX8 = PINMUX_BALL_N2_HET1_13 | PINMUX_BALL_G3_MIBSPI1NCS_2 | PINMUX_BALL_N1_HET1_15;
	
	pinMuxReg->PINMUX9 = PINMUX_BALL_W9_EQEP1B | PINMUX_BALL_V10_EQEP1I | PINMUX_BALL_J3_MIBSPI1NCS_3;
	
	pinMuxReg->PINMUX10 = PINMUX_BALL_N19_AD1EVT | PINMUX_BALL_N17_EMIF_nCS_0;
	
	pinMuxReg->PINMUX11 = PINMUX_BALL_K17_EMIF_nCS_3 | PINMUX_BALL_P1_HET1_24;
	
	pinMuxReg->PINMUX12 = PINMUX_BALL_A14_HET1_26 | PINMUX_BALL_G19_MIBSPI1NENA | PINMUX_BALL_H18_MIBSPI5NENA;
	
	pinMuxReg->PINMUX13 = PINMUX_BALL_J18_MIBSPI5SOMI_0 | PINMUX_BALL_J19_MIBSPI5SIMO_0 | PINMUX_BALL_H19_MIBSPI5CLK | PINMUX_BALL_R2_MIBSPI1NCS_0;
	
	pinMuxReg->PINMUX14 = PINMUX_BALL_E18_HET1_08 | PINMUX_BALL_K19_HET1_28 | PINMUX_BALL_D17_EMIF_nWE | PINMUX_BALL_D16_EMIF_BA_1;
	
	pinMuxReg->PINMUX15 = 0x01010101;
	
	pinMuxReg->PINMUX16 = 0x01010101;
	
	pinMuxReg->PINMUX17 = PINMUX_BALL_D19_HET1_10 | PINMUX_BALL_B4_HET1_12;
	
	pinMuxReg->PINMUX18 = PINMUX_BALL_A11_HET1_14 | PINMUX_BALL_M2_GIOB_0;
	
	pinMuxReg->PINMUX19 = PINMUX_BALL_B11_EQEP2S;
	
	pinMuxReg->PINMUX20 = PINMUX_BALL_F3_EQEP1S;
	
	pinMuxReg->PINMUX21 = PINMUX_BALL_D5_EMIF_ADDR_1 | PINMUX_BALL_K2_GIOB_1;
	
	pinMuxReg->PINMUX22 = PINMUX_BALL_D4_EMIF_ADDR_0 | PINMUX_BALL_C5_EMIF_ADDR_7 | PINMUX_BALL_C4_EMIF_ADDR_6;
	
	pinMuxReg->PINMUX23 =  0x01010100|
                               PINMUX_BALL_C6_EMIF_ADDR_8;
	
	pinMuxReg->PINMUX24 = 0x01010101;
	
	pinMuxReg->PINMUX25 = 0x01010101;
	
	pinMuxReg->PINMUX26 = 0x01010101;
	
	pinMuxReg->PINMUX27 = PINMUX_BALL_E19_MIBSPI5NCS_0;
	
	pinMuxReg->PINMUX28 = 0x01010101;
	
	pinMuxReg->PINMUX29 = PINMUX_BALL_D3_SPI2NENA;
	
	pinMuxReg->PINMUX30 = 0x01010101;

	pinMuxReg->PINMUX31 = 0x01010101;

	pinMuxReg->PINMUX32 = 0x01010101;

	pinMuxReg->PINMUX33 = PINMUX_BALL_B12_HET1_04 | PINMUX_BALL_V8_MIBSPI3SOMI | PINMUX_BALL_W8_MIBSPI3SIMO | PINMUX_BALL_V9_EQEP1A;

	pinMuxReg->PINMUX34 = PINMUX_BALL_A4_HET1_16 | PINMUX_BALL_J1_HET1_18 | PINMUX_BALL_P2_HET1_20;

/* USER CODE BEGIN (3) */
/* USER CODE END */

	
	
	PINMUX_ALT_ADC_TRIGGER_SELECT(1);
	PINMUX_ETHERNET_SELECT(RMII);
	
/* USER CODE BEGIN (4) */
/* USER CODE END */

	PINMUX_ETPWM1_EQEPERR_ENABLE(EQEPERR12);
	PINMUX_ETPWM2_EQEPERR_ENABLE(EQEPERR12);
	PINMUX_ETPWM3_EQEPERR_ENABLE(EQEPERR12);
	PINMUX_ETPWM4_EQEPERR_ENABLE(EQEPERR12);
	PINMUX_ETPWM5_EQEPERR_ENABLE(EQEPERR12);
	PINMUX_ETPWM6_EQEPERR_ENABLE(EQEPERR12);
	PINMUX_ETPWM7_EQEPERR_ENABLE(EQEPERR12);
	
	
	PINMUX_ETPWM_TZ1_ENABLE(ASYNC);
	PINMUX_ETPWM_TZ2_ENABLE(ASYNC);
	PINMUX_ETPWM_TZ3_ENABLE(ASYNC);
	PINMUX_ETPWM_EPWM1SYNCI_ENABLE(ASYNC);

/* USER CODE BEGIN (5) */
/* USER CODE END */
	
	/* Disable Pin Muxing */
	kickerReg->KICKER0 = 0x00000000;
	kickerReg->KICKER1 = 0x00000000;
	
/* USER CODE BEGIN (6) */
/* USER CODE END */
}

/* USER CODE BEGIN (7) */
/* USER CODE END */
